### ISSUE TITLE
Support netstandard2.x

### ISSUE THREAD

**Issue by galvesribeiro** [Mastercard/oauth1-signer-csharp#3] opened 2020-03-20 06:58 UTC
Hello!

I'm integrating Mastercard's APIs on our company and ended up on this package. Specifically the BIN Tables and the Account Update. 

The requests on those APIs requires the OAuth sign and the body encryption. I've tried to add the packages you guys released but I've found 3 issues:

1. The packages doesn't target `netstandard2.0` or `netstandard2.1` so I can't use them properly on a service targeting `netcoreapp3.1`;
2. Reading thru the code here, I've found a major blocking call [here](https://github.com/Mastercard/oauth1-signer-csharp/blob/master/Mastercard.Developer.OAuth1Signer.Core/Signers/NetHttpClientSigner.cs#L32-L33) which is a major/critical performance issue;
3. The NetHttp part uses old `HttpClient` which nowadays is slow and consume more resources than it should, so using `IHttpClientFactory` would be the better approach today.

So, my questions is, do you accept a PR to both update to at least `netstandard2.0` and to fix the other to problems? If yes, how long would it take to a new version be released with the changes?

If it is not possible, or the time is too long, no problem. I would implement that myself but I would be happy to contribute on fix those issues and bring the packages to the recent .Net stack.

Thanks!

**Comment by jaaufauvre** [comment] 2020-03-21 18:28
Hi @galvesribeiro,

Thanks for having opened this issue. Of course, contributions are welcomed. Please open a PR and someone will review it.

Some answers to your points:

1. `Mastercard.Developer.OAuth1Signer.Core` and `Mastercard.Developer.ClientEncryption.Core` target .NET Standard 1.3, so you should be able to add them to a .NET Core 3.1 app (I actually did that in the past and I worked).
So I'm wondering what do you mean by "_I can't use them properly on a service targeting netcoreapp3.1_"? 
Also, there is a reason why we decided to go with .NET Standard 1.3. It's because we wanted our packages to be compatible with the highest possible number of .NET implementations and some of our customers were using .NET Core 1.0 or .NET Framework 4.6 at the time we created those projects (and it could still be the case unfortunately).

2. Well spotted 👍. There is no reason why we would block the calling thread, so we can easily introduce an `async` version `Sign`. If you have a fix please submit a PR, if not, I can take care of that.

3. `NetHttpClientSigner` is an utility class you can use to sign your requests in case your application relies on `System.Net.Http.HttpClient`. 
But it doesn't mean we force the usage of `HttpClient`. For instance, `Mastercard.Developer.OAuth1Signer.RestSharp` contains a signer class for signing RestSharp Portable `IRestRequest` objects. So I would say you can still use `IHttpClientFactory` and sign your requests with `NetHttpClientSigner` or a custom signer class created on top of `OAuth.GetAuthorizationHeader`. Again, if you have some code do not hesitate to create a PR and we will be happy to review it.

Please note we try to keep the `Core` packages without dependencies (used unless absolutely necessary), for them to stay as thin as possible and avoid dependency hell.

I hope this makes sense!

**Comment by galvesribeiro** [comment] 2020-03-21 19:03
Absolutely! I've already extracted/fixed the code that was required to make my API calls to work on my project, but I'll contribute them back asap.

Regarding the `netstandard1.3`, I've added that pacakge to my `netcoreapp3.1` and it say it was restored using the older .net frameworks and we keep the yellow exclamation on VS reference.

Thanks!

**Comment by jaaufauvre** [comment] 2020-03-22 13:37
It seems the [NU1701 warning](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1701) you describe. I tried to create a  `netcoreapp3.1 ` project, but couldn't reproduce this. Can you please share the warning description?

**Comment by galvesribeiro** [comment] 2020-03-23 21:32
Jibus man, I'm sorry... I confused things...

The lib I have that warning is `MasterCard-Bintable`, not this one, sorry.

So, please ignore the warning item, it works just fine.

I'll make a PR around the other items.

Thank you!

**Comment by jaaufauvre** [comment] 2020-05-05 08:23
Hi @galvesribeiro, I wanted to check if you had some code ready for what we discussed ealier (the blocking call and maybe a new request signer class if you had to create one). 

If you don't, that's fine. I can close this issue ("_Support netstandard2.x_") and we can open separate issues for those.

Let me know 🙂

**Comment by AMCN41R** [comment] 2020-08-05 16:59
Hey,

I've created a PR for the `SignAsync` method if you'd like to use/review it... [PR-5](https://github.com/Mastercard/oauth1-signer-csharp/pull/5)

**Closed as completed** 2020-08-12 10:03 UTC
Labels: enhancement, question
